.\" Manpage for git-stale-branches
.TH man 1 "November 2017" "0.1" "git stale-branches man page"
.SH NAME
git stale-branches \- List stale branches
.SH SYNOPSIS
git stale-branches [REMOTE] [REMOTE...]
.SH DESCRIPTION
List stale branches
If REMOTE is specified, only consider this remote.
If REMOTE is omitted, defaults to all remotes.
.SH OPTIONS
No options.
.SH BUGS
No known bugs.
.SH AUTHOR
Nicolas Moreau <moreau-nicolas@users.noreply.github.com>
